/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Differential
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by CoffeeScript 1.7.1
(function() {
  var ar;

  ar = {
    signIn: "تسجيل الدخول",
    signin: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    signUp: "افتح حساب جديد",
    OR: "او",
    forgotPassword: "نسيت كلمة السر؟",
    emailAddress: "البريد الالكترونى",
    emailResetLink: "اعادة تعيين البريد الالكترونى",
    dontHaveAnAccount: "ليس عندك حساب؟",
    resetYourPassword: "اعادة تعيين كلمة السر",
    updateYourPassword: "جدد كلمة السر",
    password: "كلمة السر",
    usernameOrEmail: "اسم المستخدم او البريد الالكترونى",
    email: "البريد الالكترونى",
    ifYouAlreadyHaveAnAccount: "اذا كان عندك حساب",
    signUpWithYourEmailAddress: "سجل ببريدك الالكترونى",
    username: "اسم المستخدم",
    optional: "اختيارى",
    signupCode: "رمز التسجيل",
    clickAgree: "بفتح حسابك انت توافق على",
    privacyPolicy: "سياسة الخصوصية",
    terms: "شروط الاستخدام",
    sign: "تسجيل",
    configure: "تعديل",
    "with": "مع",
    createAccount: "افتح حساب جديد",
    and: "و",
    "Match failed": "المطابقة فشلت",
    "User not found": "اسم المستخدم غير موجود",
    error: {
      minChar: "سبعة حروف هو الحد الادنى لكلمة السر",
      pwOneLetter: "كلمة السر تحتاج الى حرف اخر",
      pwOneDigit: "كلمة السر يجب ان تحتوى على رقم واحد على الاقل",
      usernameRequired: "اسم المستخدم مطلوب",
      emailRequired: "البريد الالكترونى مطلوب",
      signupCodeRequired: "رمز التسجيل مطلوب",
      signupCodeIncorrect: "رمز التسجيل غير صحيح",
      signInRequired: "عليك بتسجبل الدخول لفعل ذلك",
      usernameIsEmail: "اسم المستخدم لا يمكن ان يكون بريد الكترونى"
    }
  };

  T9n.map("ar", ar);

}).call(this);
