/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Differential
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by CoffeeScript 1.7.1
(function() {
  var en;

  en = {
    signIn: "Sign In",
    signin: "sign in",
    signOut: "Sign Out",
    signUp: "Register",
    OR: "OR",
    forgotPassword: "Forgot your password?",
    emailAddress: "Email Address",
    emailResetLink: "Email Reset Link",
    dontHaveAnAccount: "Don't have an account?",
    resetYourPassword: "Reset your password",
    updateYourPassword: "Update your password",
    password: "Password",
    usernameOrEmail: "Username or email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "If you already have an account",
    signUpWithYourEmailAddress: "Register with your email address",
    username: "Username",
    optional: "Optional",
    signupCode: "Registration Code",
    clickAgree: "By clicking Register, you agree to our",
    privacyPolicy: "Privacy Policy",
    terms: "Terms of Use",
    sign: "Sign",
    configure: "Configure",
    "with": "with",
    createAccount: "Create an Account",
    and: "and",
    "Match failed": "Match failed",
    "User not found": "User not found",
    error: {
      minChar: "7 character minimum password.",
      pwOneLetter: "Password requires 1 letter.",
      pwOneDigit: "Password must have at least one digit.",
      usernameRequired: "Username is required.",
      emailRequired: "Email is required.",
      signupCodeRequired: "Registration code is required.",
      signupCodeIncorrect: "Registration code is incorrect.",
      signInRequired: "You must be signed in to do that.",
      usernameIsEmail: "Username cannot be an email address."
    }
  };

  T9n.map("en", en);

}).call(this);
