/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Differential
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by CoffeeScript 1.7.1
(function() {
  var fr;

  fr = {
    signIn: "Se Connecter",
    signin: "se connecter",
    signOut: "Se Deconnecter",
    signUp: "S'enregistrer",
    OR: "OU",
    forgotPassword: "Vous avez oublié votre mot de passe ?",
    emailAddress: "Adresse Email",
    emailResetLink: "Adresse pour reinitialiser votre mot de passe",
    dontHaveAnAccount: "Vous n'avez pas de compte ?",
    resetYourPassword: "Reinitialiser votre mot de passe",
    updateYourPassword: "Mettre à jour le mot de passe",
    password: "Mot de passe",
    usernameOrEmail: "Nom d'utilisateur ou email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "Si vous avez déjà un compte",
    signUpWithYourEmailAddress: "S'enregistrer avec votre adresse email",
    username: "Nom d'utilisateur",
    optional: "Optionnel",
    signupCode: "Code d'inscription",
    clickAgree: "En cliquant sur S'enregistrer, vous acceptez notre",
    privacyPolicy: "Politique de confidentialité",
    terms: "Conditions d'utilisation",
    sign: "S'enregistrer",
    configure: "Configurer",
    "with": "avec",
    createAccount: "Créer un compte",
    and: "et",
    error: {
      minChar: "Votre mot de passe doit contenir au minimum 7 caractères.",
      pwOneLetter: "Votre mot de passe doit contenir au moins une lettre.",
      pwOneDigit: "Votre mot de passe doit contenir au moins un chiffre.",
      usernameRequired: "Un nom d'utilisateur est requis.",
      emailRequired: "Un email est requis.",
      signupCodeRequired: "Un code d'inscription est requis.",
      signupCodeIncorrect: "Le code d'enregistrement est incorrect.",
      signInRequired: "Vous devez être connecté pour continuer.",
      usernameIsEmail: "Le nom d'utilisateur ne peut être le même que l'adresse email."
    }
  };

  T9n.map("fr", fr);

}).call(this);
