/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Differential
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by CoffeeScript 1.7.1
(function() {
  var de;

  de = {
    signIn: "Anmelden",
    signin: "anmelden",
    signOut: "Abmelden",
    signUp: "Registrieren",
    OR: "ODER",
    forgotPassword: "Passwort vergessen?",
    emailAddress: "E-Mail Adresse",
    emailResetLink: "Senden",
    dontHaveAnAccount: "Noch kein Konto?",
    resetYourPassword: "Passwort zurücksetzen",
    updateYourPassword: "Passwort aktualisieren",
    password: "Passwort",
    usernameOrEmail: "Benutzername oder E-Mail",
    email: "E-Mail",
    ifYouAlreadyHaveAnAccount: "Falls Sie ein Konto haben, bitte hier",
    signUpWithYourEmailAddress: "Mit E-Mail registrieren",
    username: "Benutzername",
    optional: "Optional",
    signupCode: "Registrierungscode",
    clickAgree: "Durch die Registrierung akzeptieren Sie unsere",
    privacyPolicy: "Datenschutzerklärung",
    terms: "Geschäftsbedingungen",
    sign: "Anmelden",
    configure: "Konfigurieren",
    "with": "mit",
    createAccount: "Konto erzeugen",
    and: "und",
    error: {
      minChar: "Passwort muss mindesten 7 Zeichen lang sein.",
      pwOneLetter: "Passwort muss mindestens einen Buchstaben enthalten.",
      pwOneDigit: "Passwort muss mindestens eine Ziffer enthalten.",
      usernameRequired: "Benutzername benötigt.",
      emailRequired: "E-Mail benötigt.",
      signupCodeRequired: "Registrierungscode benötigt.",
      signupCodeIncorrect: "Registrierungscode ungültig.",
      signInRequired: "Sie müssen sich anmelden.",
      usernameIsEmail: "Benutzername kann nicht eine E-Mail."
    }
  };

  T9n.map("de", de);

}).call(this);
