/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Differential
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by CoffeeScript 1.7.1
(function() {
  var it;

  it = {
    signIn: "Accedi",
    signin: "accedi",
    signOut: "Esci",
    signUp: "Registrati",
    OR: "OPPURE",
    forgotPassword: "Hai dimenticato la password?",
    emailAddress: "Indirizzo Email",
    emailResetLink: "Invia Link di Reset",
    dontHaveAnAccount: "Non hai un account?",
    resetYourPassword: "Reimposta la password",
    updateYourPassword: "Aggiorna la password",
    password: "Password",
    usernameOrEmail: "Nome utente o email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "Se hai già un account",
    signUpWithYourEmailAddress: "Registrati con il tuo indirizzo email",
    username: "Username",
    optional: "Opzionale",
    signupCode: "Codice di Registrazione",
    clickAgree: "Cliccando Registrati, accetti la nostra",
    privacyPolicy: "Privacy Policy",
    terms: "Termini di Servizio",
    sign: "Accedi",
    configure: "Configura",
    "with": "con",
    createAccount: "Crea un Account",
    and: "e",
    "Match failed": "Riscontro fallito",
    "User not found": "Utente non trovato",
    error: {
      minChar: "Password di almeno 7 caratteri.",
      pwOneLetter: "La Password deve contenere 1 lettera.",
      pwOneDigit: "La Password deve contenere almeno un numero.",
      usernameRequired: "Il Nome utente è obbligatorio.",
      emailRequired: "L'Email è obbligatoria.",
      signupCodeRequired: "Il Codice di Registrazione è obbligatorio.",
      signupCodeIncorrect: "Codice di Registrazione errato.",
      signInRequired: "Per fare questo devi accedere.",
      usernameIsEmail: "Il Nome Utente non può essere un indirizzo email."
    }
  };

  T9n.map("it", it);

}).call(this);
