/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Differential
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by CoffeeScript 1.7.1
(function() {
  var pl;

  pl = {
    signIn: "Zaloguj się",
    signin: "zaloguj się",
    signOut: "Wyloguj się",
    signUp: "Zarejestruj się",
    OR: "LUB",
    forgotPassword: "Zapomniałeś hasła?",
    emailAddress: "Adres email",
    emailResetLink: "Wyślij email z linkiem do zmiany hasła",
    dontHaveAnAccount: "Nie masz konta?",
    resetYourPassword: "Ustaw nowe hasło",
    updateYourPassword: "Zaktualizuj swoje hasło",
    password: "Hasło",
    usernameOrEmail: "Nazwa użytkownika lub email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "Jeżeli już masz konto",
    signUpWithYourEmailAddress: "Zarejestruj się używając adresu email",
    username: "Nazwa użytkownika",
    optional: "Nieobowiązkowe",
    signupCode: "Kod rejestracji",
    clickAgree: "Klikając na Zarejestruj się zgadzasz się z naszą",
    privacyPolicy: "polityką prywatności",
    terms: "warunkami korzystania z serwisu",
    sign: "Podpisz",
    configure: "Konfiguruj",
    "with": "z",
    createAccount: "Utwórz konto",
    and: "i",
    error: {
      minChar: "7 znaków to minimalna długość hasła.",
      pwOneLetter: "Hasło musi zawierać 1 literę.",
      pwOneDigit: "Hasło musi zawierać przynajmniej jedną cyfrę.",
      usernameRequired: "Wymagana jest nazwa użytkownika.",
      emailRequired: "Wymagany jest adres email.",
      signupCodeRequired: "Wymagany jest kod rejestracji.",
      signupCodeIncorrect: "Kod rejestracji jest nieprawidłowy.",
      signInRequired: "Musisz być zalogowany, aby to zrobić.",
      usernameIsEmail: "Nazwa użytkownika nie może być adres e-mail."
    }
  };

  T9n.map("pl", pl);

}).call(this);
