/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Differential
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by CoffeeScript 1.7.1
(function() {
  var pt;

  pt = {
    signIn: "Entrar",
    signin: "Entrar",
    signOut: "Sair",
    signUp: "Registrar",
    OR: "OU",
    forgotPassword: "Esqueceu sua senha?",
    emailAddress: "Endereço de e-mail",
    emailResetLink: "Gerar nova senha",
    dontHaveAnAccount: "Não tem conta?",
    resetYourPassword: "Gerar nova senha",
    updateYourPassword: "Atualizar senha",
    password: "Senha",
    usernameOrEmail: "Usuario ou e-mail",
    email: "E-mail",
    ifYouAlreadyHaveAnAccount: "Se você já tem uma conta",
    signUpWithYourEmailAddress: "Entre usando seu endereço de e-mail",
    username: "Nome de usuário",
    optional: "Opcional",
    signupCode: "Código de acesso",
    clickAgree: "Ao clicar em Entrar, você aceita nosso",
    privacyPolicy: "Política de Privacidade",
    terms: "Termos de Uso",
    sign: "Entrar",
    configure: "Configurar",
    "with": "com",
    createAccount: "Criar Conta",
    and: "e",
    "Match failed": "Usuário ou senha não encontrado",
    "User not found": "Usuário não encontrado",
    error: {
      minChar: "Senha requer um mínimo de 7 caracteres.",
      pwOneLetter: "Senha deve conter pelo menos uma letra.",
      pwOneDigit: "Senha deve conter pelo menos um digito.",
      usernameRequired: "Nome de usuário é obrigatório.",
      emailRequired: "E-mail é obrigatório.",
      signupCodeRequired: "É necessário um código de acesso.",
      signupCodeIncorrect: "Código de acesso incorreto.",
      signInRequired: "Você precisa estar logado para fazer isso.",
      usernameIsEmail: "Nome de usuário não pode ser um endereço de e-mail."
    }
  };

  T9n.map("pt", pt);

}).call(this);
