/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Differential
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by CoffeeScript 1.7.1
(function() {
  var ru;

  ru = {
    signIn: "Войти",
    signin: "Войти",
    signOut: "Выйти",
    signUp: "Регистрация",
    OR: "ИЛИ",
    forgotPassword: "Забыли пароль?",
    emailAddress: "Email",
    emailResetLink: "Отправить ссылку для сброса",
    dontHaveAnAccount: "Нет аккаунта?",
    resetYourPassword: "Сбросить пароль",
    updateYourPassword: "Обновить пароль",
    password: "Пароль",
    usernameOrEmail: "Имя пользователя или email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "Если у вас уже есть аккаунт",
    signUpWithYourEmailAddress: "Зарегистрируйтесь с вашим email адресом",
    username: "Имя пользователя",
    optional: "Необязательно",
    signupCode: "Регистрационный код",
    clickAgree: "Нажав на Регистрация вы соглашаетесь с условиями",
    privacyPolicy: "Политики безопасности",
    terms: "Условиями пользования",
    sign: "Подпись",
    configure: "Конфигурировать",
    "with": "с",
    createAccount: "Создать аккаунт",
    and: "и",
    "Match failed": "Не совпадают",
    "User not found": "Пользователь не найден",
    error: {
      minChar: "Минимальное кол-во символов для пароля 7.",
      pwOneLetter: "В пароле должна быть хотя бы одна буква.",
      pwOneDigit: "В пароле должна быть хотя бы одна цифра.",
      usernameRequired: "Имя пользователя обязательно.",
      emailRequired: "Email обязательно.",
      signupCodeRequired: "Необходим регистрациооный код.",
      signupCodeIncorrect: "Неправильный регистрационный код.",
      signInRequired: "Необходимо войти для чтобы продолжить.",
      usernameIsEmail: "Имя пользователя не может быть адресом email."
    }
  };

  T9n.map("ru", ru);

}).call(this);
