/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Differential
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by CoffeeScript 1.7.1
(function() {
  var sl;

  sl = {
    signIn: "Prijava",
    signin: "se prijavi",
    signOut: "Odjava",
    signUp: "Registracija",
    OR: "ALI",
    forgotPassword: "Pozabljeno geslo?",
    emailAddress: "Email naslov",
    emailResetLink: "Pošlji ponastavitveno povezavo",
    dontHaveAnAccount: "Nisi registriran(a)?",
    resetYourPassword: "Ponastavi geslo",
    updateYourPassword: "Spremeni geslo",
    password: "Geslo",
    usernameOrEmail: "Uporabniško ime ali email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "Če si že registriran(a),",
    signUpWithYourEmailAddress: "Prijava z email naslovom",
    username: "Uporabniško ime",
    optional: "Po želji",
    signupCode: "Prijavna koda",
    clickAgree: "S klikom na Registracija se strinjaš",
    privacyPolicy: "z našimi pogoji uporabe",
    terms: "Pogoji uporabe",
    sign: "Prijava",
    configure: "Nastavi",
    "with": "z",
    createAccount: "Nova registracija",
    and: "in",
    "Match failed": "Prijava neuspešna",
    "User not found": "Uporabnik ne obstaja",
    "Incorrect password": "Napačno geslo",
    "Email already exists.": "Email že obstaja.",
    "Email is required": "Email je obvezen podatek",
    error: {
      minChar: "Geslo mora imeti vsaj sedem znakov.",
      pwOneLetter: "V geslu mora biti vsaj ena črka.",
      pwOneDigit: "V geslu mora biti vsaj ena številka.",
      usernameRequired: "Uporabniško ime je obvezen vnos.",
      emailRequired: "Email je obvezen vnos.",
      signupCodeRequired: "Prijavna koda je obvezen vnos.",
      signupCodeIncorrect: "Prijavna koda je napačna.",
      signInRequired: "Za to moraš biti prijavljen(a).",
      usernameIsEmail: "Uporabniško ime ne more biti email naslov."
    }
  };

  T9n.map("sl", sl);

}).call(this);
