/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Differential
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by CoffeeScript 1.7.1
(function() {
  var es;

  es = {
    signIn: "Entrar",
    signOut: "Salir",
    signUp: "Suscribir",
    OR: "O",
    forgotPassword: "Contraseña olvidada?",
    emailAddress: "Dirección de Email",
    emailResetLink: "Reiniciar Email",
    dontHaveAnAccount: "No tenés una cuenta?",
    resetYourPassword: "Resetear tu contraseña",
    updateYourPassword: "Actualizar tu contraseña",
    password: "Contraseña",
    usernameOrEmail: "Usuario o email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "Si ya tenés una cuenta",
    signUpWithYourEmailAddress: "Suscribir con tu email",
    username: "Usuario",
    optional: "Opcional",
    signupCode: "Codigo para suscribir",
    clickAgree: "Si haces clic en Sucribir estas de acuerdo con la",
    privacyPolicy: "Póliza de Privacidad",
    terms: "Terminos de Uso",
    sign: "Ingresar",
    configure: "Disposición",
    "with": "con",
    createAccount: "Crear cuenta",
    and: "y",
    error: {
      minChar: "7 carácteres mínimo.",
      pwOneLetter: "mínimo una letra.",
      pwOneDigit: "mínimo un dígito.",
      usernameRequired: "Usuario es necesario.",
      emailRequired: "Email es necesario.",
      signupCodeRequired: "Código para suscribir es necesario.",
      signupCodeIncorrect: "Código para suscribir no coincide.",
      signInRequired: "Debes iniciar sesión para hacer eso.",
      usernameIsEmail: "Usuario no puede ser Email."
    }
  };

  T9n.map("es", es);

}).call(this);
