/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Differential
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by CoffeeScript 1.7.1
(function() {
  var sv;

  sv = {
    signIn: "Logga in",
    signin: "logga in",
    signOut: "Logga ut",
    signUp: "Skapa konto",
    OR: "ELLER",
    forgotPassword: "Glömt din e-postadress?",
    emailAddress: "E-postadress",
    emailResetLink: "E-post återställningslänk",
    dontHaveAnAccount: "Har du inget konto?",
    resetYourPassword: "Återställ ditt lösenord",
    updateYourPassword: "Uppdatera ditt lösenord",
    password: "Lösenord",
    usernameOrEmail: "Användarnamn eller e-postadress",
    email: "E-postadress",
    ifYouAlreadyHaveAnAccount: "Om du redan har ett konto",
    signUpWithYourEmailAddress: "Skapa ett konto med din e-postadress",
    username: "Användarnamn",
    optional: "Valfri",
    signupCode: "Registreringskod",
    clickAgree: "När du väljer att skapa ett konto så godkänner du också vår",
    privacyPolicy: "integritetspolicy",
    terms: "användarvilkor",
    sign: "Logga",
    configure: "Konfigurera",
    "with": "med",
    createAccount: "Skapa ett konto",
    and: "och",
    "Match failed": "Matchning misslyckades",
    "User not found": "Användaren hittades inte",
    error: {
      minChar: "Det krävs minst 7 tecken i ditt lösenord.",
      pwOneLetter: "Lösenordet måste ha minst 1 bokstav.",
      pwOneDigit: "Lösenordet måste ha minst 1 siffra.",
      usernameRequired: "Det krävs ett användarnamn.",
      emailRequired: "Det krävs ett lösenord.",
      signupCodeRequired: "Det krävs en registreringskod.",
      signupCodeIncorrect: "Registreringskoden är felaktig.",
      signInRequired: "Inloggning krävs här.",
      usernameIsEmail: "Användarnamnet kan inte vara en e-postadress."
    }
  };

  T9n.map("sv", sv);

}).call(this);
